"""One-shot generator for the B3–D4 task split. Not part of the product."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "tasks.yaml"

FORBIDDEN = [
    "evals/reports/rag-v0.1-baseline-20260919.json",
    "生产数据",
    "生产密钥",
    ".env",
]

ITEMS = [
    ("QA-001", "对话默认检索本租户当前版（交付 B3）", "P0", "2026-11-13", ["TEN-003"], "L1", "enable-tenant-current-rag",
     "成员提问时默认不检索本租户文档。",
     ["RAG_ENABLED 默认为 false，关闭时对话跳过检索。", "检索读路径已按租户和当前版过滤，已软删除文档不进入检索。"],
     ["app/core/config.py", "app/services/chat_service.py", "app/rag/service.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/services/chat_service.py", "app/core/config.py", "tests/", "tasks.yaml", "AGENTS.md"],
     ["安装后的默认对话会检索本租户已发布当前版", "另一租户和已软删除文档不进入上下文"],
     ["不改切分、Embedding 或 RRF", "不做独立重排", "不展示来源（归 QA-002、QA-003）"],
     ["本租户当前版可被注入", "跨租户与已删除文档不出现", "相关 pytest 通过"],
     ["本租户当前版命中", "跨租户不命中", "已删除文档不命中"],
     ["pytest tests/ -k 'chat or rag' -v", "ruff check app/"]),
    ("QA-002", "回复携带来源字段（交付 B3）", "P0", "2026-11-13", ["QA-001"], "L1", "chat-source-fields",
     "回复没有稳定的来源字段，调用方无法知道用了哪份文件。",
     ["回答目前主要是文本，没有文件名、页码或段落字段。"],
     ["app/services/chat_service.py", "docs/product/as-is-capability-matrix.md"],
     ["docs/plans/plan_remaining_delivery.md", "app/schemas/", "app/services/chat_service.py", "tests/", "tasks.yaml", "AGENTS.md"],
     ["命中文档时响应含文件名", "解析结果已有页码或段落时一并返回", "无命中时来源为空"],
     ["不做引用角标和原文侧栏", "不新增引用准确率评测"],
     ["有命中时含文件名", "无页码时不编造页码", "无命中时来源为空"],
     ["有文件名", "不编造页码", "无命中为空"],
     ["pytest tests/ -k 'chat or citation or source' -v", "ruff check app/"]),
    ("QA-003", "对话页展示来源（交付 B3）", "P0", "2026-11-13", ["QA-002"], "L0", "chat-show-sources",
     "对话页不展示回复用了哪份文件。",
     ["前端对话组件没有渲染来源字段。"],
     ["frontend/src/pages/Chat.tsx", "frontend/src/components/chat/"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["有来源时展示文件名", "已有页码或段落时一起展示", "无来源时不显示空区块"],
     ["不做引用跳转和原文侧栏"],
     ["页面能看到文件名", "前端类型检查与构建通过"],
     ["展示文件名", "无来源不显示空块"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("QA-004", "知识库上传、状态、重建、删除与软删除一致（交付 B3）", "P0", "2026-11-13", ["QA-001"], "L1", "kb-soft-delete-console",
     "知识库页的上传、状态、重建、删除尚未按软删除核对完整。",
     ["删除写入 deleted_at。成员列表默认看不到已删文档。", "控制台知识库页已有上传和删除确认。"],
     ["app/rag/service.py", "frontend/src/pages/Knowledge.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/rag/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["上传后能看到处理状态", "重建不把已删文档救回当前版", "删除后成员不可见，管理员仍能看到已删标记"],
     ["不做切分细节可视化", "不改保留期", "不做物理清理"],
     ["成员删除后列表不可见且提问不再命中", "管理员能看到已删", "重建不恢复已删文档"],
     ["成员看不到已删", "管理员看得到已删", "重建不恢复"],
     ["pytest tests/ -k 'rag or document' -v", "cd frontend; npm run typecheck"]),
    ("AUTH-001", "注册并加入默认租户（交付 C1）", "P0", "2026-11-21", ["TEN-003"], "L1", "public-register",
     "新用户不能自己注册并进入默认租户。",
     ["认证路由只有登录和刷新。", "默认租户和环境变量管理员已经存在。"],
     ["app/api/routes/auth.py", "app/services/auth_service.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "app/schemas/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["公开注册成功后成为默认租户的 member", "用户名全局唯一", "注册响应不含密码"],
     ["不做邀请码", "不建成员表", "不做 /setup", "不实现 CLI"],
     ["注册后可登录且令牌租户为默认租户", "重复用户名被拒绝", "响应不含密码"],
     ["注册后租户正确", "重名拒绝", "响应无密码"],
     ["pytest tests/ -k auth -v", "ruff check app/"]),
    ("AUTH-002", "管理员撤销用户令牌（交付 C1）", "P0", "2026-11-21", ["AUTH-001"], "L2", "revoke-token-version",
     "管理员不能让已发出的刷新令牌失效。",
     ["刷新会核对 token_version。", "没有递增 token_version 的管理接口。"],
     ["app/core/security.py", "app/api/routes/auth.py", "app/models/user.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["系统管理员可撤销指定用户", "旧刷新令牌失败", "撤销写入审计"],
     ["不在本任务做停用用户的全部语义（归 ADM-001）", "不改访问令牌的有效期"],
     ["撤销后旧 refresh 失败", "新登录成功", "非管理员 403"],
     ["旧刷新失败", "重新登录成功", "非管理员 403"],
     ["pytest tests/ -k 'auth or token' -v", "ruff check app/"]),
    ("AUTH-003", "注册页与首次设置向导（交付 C1）", "P0", "2026-11-21", ["AUTH-001"], "L1", "register-and-setup-pages",
     "没有管理员时，控制台不能引导完成第一次建号。",
     ["只有登录页。管理员靠环境变量创建。"],
     ["frontend/src/pages/Login.tsx", "app/services/auth_service.py"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "app/api/routes/", "tasks.yaml", "AGENTS.md"],
     ["注册页可完成注册并进入对话", "没有系统管理员时进入 /setup", "已有管理员时 /setup 不可用"],
     ["不实现 CLI", "不强制首次登录改密"],
     ["空库能走完向导", "完成后再次访问进不了向导", "注册页能登录"],
     ["空库向导", "向导只此一次", "注册可登录"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("AUTH-004", "首次运行旅程与 README 逐步一致（交付 C1）", "P0", "2026-11-21", ["AUTH-003"], "L0", "readme-first-run",
     "README 的快速开始和第一次使用的页面步骤不一致。",
     ["产品旅程写了 CLI init，交付排期把 CLI 放在 D3。", "C1 的路径是环境变量或 /setup，加上注册和登录。"],
     ["README.md", "docs/plans/plan_delivery_2027-03-25.md"],
     ["docs/plans/plan_remaining_delivery.md", "README.md", "docs/", "tasks.yaml", "AGENTS.md"],
     ["README 按填写环境、启动、建管理员、注册或登录、发送第一条消息书写", "每步写明失败时看哪里"],
     ["不实现 ai-assistant init", "不把首次镜像下载算进计时"],
     ["按 README 能走到发出一条消息", "文档中的路径在控制台存在"],
     ["步骤与页面一致", "失败时有下一步"],
     ["按 README 手工核对一次并记录结果"]),
    ("INV-001", "邀请码加入租户（交付 C2）", "P0", "2026-11-28", ["AUTH-001"], "L2", "invite-membership",
     "已注册用户不能凭邀请码加入另一个租户。",
     ["用户通过 users.tenant_id 只归属一个租户。", "没有邀请码和成员表。"],
     ["app/models/user.py", "docs/plans/plan_b2_tenants.md"],
     ["docs/plans/plan_remaining_delivery.md", "app/models/", "app/api/routes/", "app/services/", "app/schemas/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["成员表记录用户在租户中的角色", "现有用户迁移为一条成员记录", "租户管理员可生成邀请码，已注册用户可接受"],
     ["不做邮件", "不在本任务切换令牌（归 INV-002）"],
     ["凭码加入后成员关系存在", "重复加入、过期或用尽被拒绝", "审计有记录"],
     ["加入成功", "重复加入拒绝", "过期码拒绝"],
     ["pytest tests/ -k 'invite or member' -v", "ruff check app/"]),
    ("INV-002", "校验成员身份后切换租户（交付 C2）", "P0", "2026-11-28", ["INV-001"], "L2", "switch-tenant",
     "加入多个租户后不能换成另一个租户的会话。",
     ["令牌租户来自用户上的单个 tenant_id。"],
     ["app/core/security.py", "app/models/user.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "app/core/security.py", "tests/", "tasks.yaml", "AGENTS.md"],
     ["是成员才换发新令牌", "当前 tenant_id 改为目标租户", "不是成员则 403 且令牌不变"],
     ["不接受查询参数传租户", "不通过切换改变系统角色"],
     ["切换后列表属于新租户", "非成员 403"],
     ["成员切换成功", "非成员 403"],
     ["pytest tests/ -k 'switch or tenant' -v", "ruff check app/"]),
    ("INV-003", "邀请入口与切换入口（交付 C2）", "P0", "2026-11-28", ["INV-002"], "L1", "invite-switch-ui",
     "页面上不能生成邀请码，也不能切换租户。",
     ["控制台没有邀请入口和顶栏切换。"],
     ["frontend/src/components/layout/", "frontend/src/App.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["租户管理员可生成邀请码", "已登录用户可输入邀请码", "多个租户时可从顶栏切换"],
     ["不做邮件", "不做六态全集"],
     ["页面能生成、接受并切换", "切换后对话列表属于新租户"],
     ["生成并接受", "切换后数据范围正确"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("ADM-001", "用户列表、改角色与停用（交付 C3）", "P0", "2026-12-09", ["AUTH-002"], "L2", "admin-user-lifecycle",
     "系统管理员不能查看用户、修改角色或停用用户。",
     ["用户页只能创建成员。停用应递增 token_version。"],
     ["frontend/src/pages/Users.tsx", "app/models/user.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["分页列出用户", "可修改角色", "停用后旧刷新失败，且不能停用自己"],
     ["不做租户管理员的成员管理页", "不物理删除用户"],
     ["列表可见", "新令牌角色已变", "停用后旧刷新失败", "非系统管理员 403"],
     ["列表", "改角色", "停用失效", "非管理员 403"],
     ["pytest tests/ -k 'user or auth' -v", "cd frontend; npm run typecheck"]),
    ("ADM-002", "租户编辑与停用（交付 C3）", "P0", "2026-12-09", ["TEN-001"], "L2", "admin-tenant-lifecycle",
     "系统管理员不能修改或停用租户。",
     ["只能创建和列出未停用租户。未停用名称唯一。"],
     ["app/api/routes/admin_tenants.py", "app/services/tenant_admin.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["可修改未停用租户的名称", "停用后该租户用户不能继续访问", "管理页能看到已停用租户"],
     ["不物理删除租户", "不在本任务做六态"],
     ["改名成功", "停用后成员不能访问", "重名被拒绝"],
     ["改名", "停用拒绝访问", "重名拒绝"],
     ["pytest tests/ -k tenant -v", "ruff check app/"]),
    ("ADM-003", "系统状态（交付 C3）", "P0", "2026-12-09", ["TEN-003"], "L0", "admin-system-status",
     "管理页看不到数据库和向量库是否连通。",
     ["健康检查已包含数据库与向量库连通性。没有系统状态页。"],
     ["app/api/routes/", "frontend/src/App.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["管理接口返回数据库连通、向量库连通和能证明的版本或启动信息", "系统状态页展示这些字段"],
     ["不做监控大盘", "不编造在线人数或调用量"],
     ["管理员能看到连通状态", "非管理员进不了"],
     ["连通状态可见", "非管理员被拦"],
     ["pytest tests/ -k 'health or status' -v", "cd frontend; npm run typecheck"]),
    ("ADM-004", "用户、租户、审计、系统状态四页六态（交付 C3）", "P0", "2026-12-09", ["ADM-001", "ADM-003"], "L1", "admin-six-states",
     "四页缺少加载、空、错误、无权限、成功、失败。",
     ["租户页和用户页只有创建结果。审计页已有列表。"],
     ["frontend/src/pages/Tenants.tsx", "frontend/src/pages/Users.tsx", "frontend/src/pages/Audit.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["四页补齐六态", "无权限有说明", "停用和删除有成功或失败反馈"],
     ["不改对话页和知识库页的六态", "不做租户设置页"],
     ["逐页能区分空、错误和无权限", "破坏性操作有反馈", "前端构建通过"],
     ["空态", "错误态", "无权限", "操作反馈"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("CHAT-001", "停止生成（交付 C4）", "P0", "2026-12-16", ["TEN-003"], "L1", "stop-generation",
     "生成过程中不能停止，已生成内容也没有停住标记。",
     ["对话使用流式输出。没有取消正在运行的生成。"],
     ["frontend/src/pages/Chat.tsx", "app/services/chat_service.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["流式期间可停止", "停止后保留已输出内容并标记已停止"],
     ["不做重新生成", "不做对话分支"],
     ["停止后不再追加", "刷新后内容仍在且带已停止标记"],
     ["停止后不再追加", "刷新仍可见"],
     ["pytest tests/ -k chat -v", "cd frontend; npm run typecheck"]),
    ("CHAT-002", "断线后查看完整回复（交付 C4）", "P0", "2026-12-16", ["CHAT-001"], "L1", "reload-finished-reply",
     "流中断后不能取回已经完成的回复。",
     ["页面没有加载完整回复的入口。"],
     ["frontend/src/hooks/useChatStream.ts", "app/services/chat_service.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["运行结束后可加载完整助手消息", "运行进行中时只提示中断，不显示成已完成"],
     ["不保证网络层自动重连", "不做多端同步"],
     ["结束后能拉回完整消息", "进行中不会显示成已完成"],
     ["完整回复可加载", "进行中不谎报完成"],
     ["pytest tests/ -k chat -v", "cd frontend; npm run typecheck"]),
    ("CHAT-003", "会话重命名与删除（交付 C4）", "P0", "2026-12-16", ["TEN-003"], "L1", "conversation-rename-delete",
     "用户不能重命名或删除自己的会话。",
     ["会话已有标题字段。控制台没有重命名和删除。"],
     ["app/models/conversation.py", "frontend/src/components/chat/ConversationList.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["本人可重命名和删除自己的会话", "删除前确认", "删除后不能再打开"],
     ["不删除他人会话", "不做会话搜索"],
     ["改名后列表更新", "删除后本人不可打开", "删除他人会话被拒绝"],
     ["改名", "删除", "不能删他人"],
     ["pytest tests/ -k conversation -v", "cd frontend; npm run typecheck"]),
    ("CHAT-004", "只读成员不能发送（交付 C4）", "P0", "2026-12-16", ["TEN-003"], "L1", "viewer-cannot-send",
     "viewer 仍可能发送消息。",
     ["角色中有 viewer。对话页没有禁用发送。"],
     ["app/core/security.py", "frontend/src/components/chat/Composer.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["viewer 发送被拒绝", "输入框禁用并说明原因"],
     ["不改变 member 的发送权限"],
     ["viewer 发送返回 403", "页面不能发出", "member 仍可发送"],
     ["viewer 403", "输入框禁用", "member 可发送"],
     ["pytest tests/ -k 'chat or viewer' -v", "cd frontend; npm run typecheck"]),
    ("CHAT-005", "会话隔离回归（交付 C4）", "P0", "2026-12-16", ["CHAT-003"], "L0", "conversation-isolation",
     "会话隔离没有按本交付包留下回归证据。",
     ["列表按用户和租户过滤。系统管理员的知识库列表仍跨租户。"],
     ["app/services/chat_service.py", "tests/"],
     ["docs/plans/plan_remaining_delivery.md", "tests/", "tasks.yaml", "AGENTS.md"],
     ["成员看不到其他租户会话", "同一租户成员看不到彼此会话", "用例写明系统管理员的现有范围"],
     ["不改资源级 ACL", "不改变系统管理员的知识库跨租户列表"],
     ["隔离用例通过", "每个身份的可见范围写在用例说明里"],
     ["跨租户不可见", "同租户他人不可见"],
     ["pytest tests/ -k 'conversation or tenant' -v"]),
    ("ROUTE-001", "按任务类型路由并按兜底链降级（交付 C5）", "P0", "2026-12-22", ["TEN-003"], "L1", "model-route-fallback",
     "不能按任务类型选择模型，主模型失败时也不能降级。",
     ["工厂按单个 LLM_PROVIDER 创建客户端。缺密钥时开发环境降为 Mock。"],
     ["app/llm/factory.py", "app/core/config.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/llm/", "app/core/config.py", ".env.example", "tests/", "tasks.yaml", "AGENTS.md"],
     ["至少两个提供商", "对话和意图可走不同配置", "主配置失败时按兜底链尝试"],
     ["不做控制台录入模型", "密钥不落库", "不更换 Embedding"],
     ["任务类型命中对应配置", "失败时走到下一家", "日志不含密钥"],
     ["类型路由", "兜底降级", "日志无密钥"],
     ["pytest tests/ -k 'llm or route' -v", "ruff check app/"]),
    ("ROUTE-002", "无可用模型时的引导（交付 C5）", "P0", "2026-12-22", ["ROUTE-001"], "L0", "missing-model-guide",
     "没有可用模型时，对话页不说明下一步。",
     ["开发环境会降到 Mock。页面没有引导。"],
     ["frontend/src/pages/Chat.tsx", "app/llm/factory.py"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["无可用真实模型时提示修改环境变量并重启", "不把 Mock 说成生产模型已接入"],
     ["不做管理端模型表单"],
     ["无密钥时能看到引导", "配好并重启后引导消失"],
     ["显示引导", "配置恢复后引导消失"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("SAND-001", "沙箱文件隔离、资源限制与进程树结束（交付 C5）", "P0", "2026-12-22", ["TEN-003"], "L2", "sandbox-isolation",
     "代码执行仍可能接触沙箱外文件，超时后进程树不一定结束。",
     ["沙箱已有 AST 白名单、子进程和超时。文件隔离与进程树结束仍是骨架。"],
     ["app/agents/tools/sandbox/sandbox.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/agents/tools/sandbox/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["执行目录与宿主机工作区隔离", "保留现有资源限制", "超时或失败时进程树结束"],
     ["不引入新的远程沙箱", "不开放网络访问"],
     ["用例读不到沙箱外的指定文件", "超时后没有残留子进程"],
     ["文件隔离", "进程树结束"],
     ["pytest tests/ -k sandbox -v", "ruff check app/"]),
    ("SAND-002", "代码执行结果展示（交付 C5）", "P0", "2026-12-22", ["SAND-001"], "L0", "sandbox-result-ui",
     "沙箱的输出、错误和超时原因没有单独展示。",
     ["工具结果混在对话文本里。"],
     ["frontend/src/components/chat/", "app/agents/tools/builtin.py"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["成功时显示标准输出", "失败或超时时显示原因", "不展示宿主机路径"],
     ["不做独立代码运行页"],
     ["成功能看到输出", "失败或超时能看到原因"],
     ["成功输出", "失败原因"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("SEC-001", "上传类型与大小限制（交付 C6）", "P0", "2026-12-25", ["QA-004"], "L1", "upload-limits",
     "不支持的类型和过大文件没有稳定的拒绝结果。",
     ["解析器按格式注册。上传限制尚未按本交付包核对。"],
     ["app/rag/", "frontend/src/pages/Knowledge.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/rag/", "app/core/config.py", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["类型和大小来自配置", "超出时返回稳定错误", "页面显示该错误"],
     ["不扩大解析格式范围"],
     ["非法类型和大文件被拒绝", "允许的小文件仍可上传"],
     ["非法类型拒绝", "超大拒绝", "小文件通过"],
     ["pytest tests/ -k upload -v", "cd frontend; npm run typecheck"]),
    ("SEC-002", "日志脱敏与界面错误提示（交付 C6）", "P0", "2026-12-25", ["TEN-003"], "L1", "redact-and-ui-errors",
     "失败时页面可能露出堆栈，日志里可能出现密钥或令牌。",
     ["已有日志脱敏工具。界面仍可能直接展示接口原文。"],
     ["app/security/", "frontend/src/lib/http.ts"],
     ["docs/plans/plan_remaining_delivery.md", "app/security/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["对话、登录、上传的日志不含密钥、令牌和密码", "这些失败在页面上不显示堆栈"],
     ["不重写全部错误码", "不把内部异常返回给浏览器"],
     ["页面无堆栈", "日志样本无密钥和令牌"],
     ["页面无堆栈", "日志无密钥"],
     ["pytest tests/ -k 'security or log' -v", "cd frontend; npm run typecheck"]),
    ("SEC-003", "Milvus 五条门槛核对（交付 C6）", "P0", "2026-12-25", ["INST-002"], "L0", "milvus-gate-check",
     "Milvus 五条门槛没有完整证据，不能判断向量库是否完成。",
     ["默认向量库仍是 Local。五条未过不得改默认。"],
     ["docs/adr/0002-official-vectorstore.md", "app/rag/vectorstore/milvus.py"],
     ["docs/plans/plan_remaining_delivery.md", "docs/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["逐条记录摄取、重解析、删除、租户过滤、回滚", "未通过时默认保持 Local"],
     ["不把 skip 当成通过", "不改写已冻结检索基线", "本任务不提前修改默认向量库"],
     ["每条都有命令和结果", "未通过时默认仍是 Local"],
     ["五条记录齐全", "默认未提前切换"],
     ["按 ADR-0002 第 5 节逐条执行并记录"]),
    ("SEC-004", "16/20 交付包清点（交付 C6）", "P0", "2026-12-25", ["SEC-001", "SEC-003", "CHAT-005", "ROUTE-002", "SAND-002"], "L0", "mvp-80-checklist",
     "前 16 个交付包没有一份带证据的清点。",
     ["第 1 到第 5 项已完成。第 6 到第 16 项对应本批任务。"],
     ["docs/plans/plan_delivery_2027-03-25.md", "tasks.yaml"],
     ["docs/plans/", "tasks.yaml", "AGENTS.md"],
     ["逐项写明完成或未完成", "缺证据的项不挪出分母"],
     ["不实现新功能", "不把 D1 到 D4 算进 80%"],
     ["清点覆盖第 6 节 1 到 16 项", "每项有证据"],
     ["16 项都有结论"],
     ["核对 tasks.yaml 状态与对应验证记录"]),
    ("FLOW-001", "调度在目标环境可启动（交付 D1）", "P1", "2027-01-15", ["SEC-004"], "L1", "workflow-scheduler-start",
     "目标环境里工作流调度不能稳定启动和停止。",
     ["未安装调度依赖时，调度测试不能运行。"],
     ["app/workflow/", "tests/test_workflow.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/workflow/", "pyproject.toml", "tests/", "tasks.yaml", "AGENTS.md"],
     ["目标环境包含调度依赖", "启动和停止测试通过"],
     ["不做拖拽编排", "不另做一套运行时"],
     ["目标环境中启动和停止测试通过"],
     ["可启动", "可停止"],
     ["pytest tests/test_workflow.py -v"]),
    ("MEM-001", "超窗压缩回归（交付 D1）", "P1", "2027-01-15", ["SEC-004"], "L0", "memory-overflow-regression",
     "超窗压缩没有本交付包要求的回归记录。",
     ["已有对话裁剪和压缩。"],
     ["app/memory/", "tests/test_context_merge.py"],
     ["docs/plans/plan_remaining_delivery.md", "tests/", "app/memory/", "tasks.yaml", "AGENTS.md"],
     ["固定长对话证明压缩发生", "最近消息仍保留"],
     ["不做长期记忆", "不改检索预算实验"],
     ["超窗用例通过", "记录保留了哪些消息"],
     ["发生压缩", "最近消息仍在"],
     ["pytest tests/ -k 'memory or context' -v"]),
    ("FLOW-002", "工作流页失败态与空态（交付 D1）", "P1", "2027-01-15", ["FLOW-001"], "L0", "workflow-empty-failed",
     "工作流页分不清没有数据和执行失败。",
     ["已有工作流页。失败态和空态未补齐。"],
     ["frontend/src/pages/Workflows.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["无工作流时显示空状态", "执行失败时显示原因"],
     ["不做新的工作流类型"],
     ["空列表和失败执行可以区分"],
     ["空态", "失败态"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("SKILL-001", "创建技能并在对话中选用（交付 D2）", "P1", "2027-02-05", ["FLOW-001"], "L1", "skill-create-select",
     "用户不能创建技能，对话也不会按条件选用。",
     ["可以从 YAML 注册技能。选用条件不完整。"],
     ["app/agents/skills/manager.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/agents/skills/", "app/api/routes/", "app/services/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["成员可创建本租户技能", "符合条件时对话选用并留下技能名", "看不到其他租户技能"],
     ["不做技能市场", "技能不直接访问数据库"],
     ["符合条件时选用", "其他租户不可见", "不符合条件时不选用"],
     ["选用成功", "跨租户不可见", "条件不符不选用"],
     ["pytest tests/ -k skill -v", "ruff check app/"]),
    ("SKILL-002", "技能管理页（交付 D2）", "P1", "2027-02-05", ["SKILL-001"], "L1", "skill-admin-page",
     "控制台不能创建和查看技能。",
     ["没有技能管理页。"],
     ["frontend/src/App.tsx", "frontend/src/components/layout/Sidebar.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["成员可在页面创建并看到技能", "失败时显示错误", "viewer 不能创建"],
     ["不做技能市场和版本对比"],
     ["创建后列表可见", "viewer 不能提交"],
     ["列表可见", "viewer 被拒"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("SUP-001", "Supervisor 分派并返回结果（交付 D2）", "P1", "2027-02-05", ["SKILL-001"], "L1", "supervisor-delegate",
     "打开 Supervisor 时，不能证明任务分给了子代理并带回结果。",
     ["Supervisor 是可选编排。默认仍是五阶段管线。"],
     ["app/agents/supervisor.py", "app/core/config.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/agents/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["显式打开时完成一次分派并返回结果", "默认配置仍走五阶段管线"],
     ["不把默认编排改成 Supervisor", "不重写五阶段管线"],
     ["测试能看到分派和汇总", "默认配置不变"],
     ["分派并返回", "默认路径不变"],
     ["pytest tests/ -k supervisor -v"]),
    ("SUP-002", "任务过程展示（交付 D2）", "P1", "2027-02-05", ["SUP-001"], "L0", "supervisor-progress-ui",
     "用户看不到子任务正在执行。",
     ["对话有阶段展示，没有子代理过程。"],
     ["frontend/src/components/chat/StageTracker.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "frontend/src/", "tasks.yaml", "AGENTS.md"],
     ["Supervisor 路径展示子任务名称和结果", "默认管线不显示该区块"],
     ["不做图形化编排"],
     ["打开 Supervisor 时能看到子任务", "默认对话不出现该区块"],
     ["能看到子任务", "默认不出现"],
     ["cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("QUOTA-001", "租户配额与超限拒绝（交付 D3）", "P1", "2027-03-05", ["SEC-004"], "L1", "tenant-quota",
     "租户超出消息或存储额度时，对话和上传仍会继续。",
     ["没有租户配额。限流只覆盖瞬时速率。"],
     ["app/security/rate_limiter.py", "app/models/user.py"],
     ["docs/plans/plan_remaining_delivery.md", "app/models/", "app/services/", "app/api/routes/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["可设置消息数和存储上限", "对话前检查消息额度", "上传前检查存储", "超限不写入半截结果"],
     ["不计费", "不做用户级配额", "不把 Token 账单作为本任务门槛"],
     ["未超限可成功", "超限被拒绝且没有新增对话或文档"],
     ["额度内成功", "超限无写入"],
     ["pytest tests/ -k quota -v", "ruff check app/"]),
    ("LIMIT-001", "限流提示与倒计时（交付 D3）", "P1", "2027-03-05", ["SEC-004"], "L1", "rate-limit-countdown",
     "被限流时页面不说明要等多久。",
     ["对话入口已有限流器。页面没有倒计时。"],
     ["app/security/rate_limiter.py", "frontend/src/pages/Chat.tsx"],
     ["docs/plans/plan_remaining_delivery.md", "app/security/", "frontend/src/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["限流响应含剩余等待时间", "对话页显示倒计时"],
     ["不替换限流算法，除非它给不出剩余时间"],
     ["超额后出现倒计时", "未超限时不出现"],
     ["有倒计时", "未超限不出现"],
     ["pytest tests/ -k rate -v", "cd frontend; npm run typecheck"]),
    ("EXPORT-001", "导出租户对话（交付 D3）", "P1", "2027-03-05", ["SEC-004"], "L1", "export-tenant-chats",
     "租户管理员不能导出本租户对话。",
     ["没有导出接口。"],
     ["app/services/chat_service.py", "app/audit/"],
     ["docs/plans/plan_remaining_delivery.md", "app/api/routes/", "app/services/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["租户管理员导出本租户对话 JSON", "导出写入审计", "不能导出其他租户"],
     ["不训练模型", "不导出其他租户"],
     ["文件只含本租户", "其他角色或租户被拒绝", "审计有记录"],
     ["只含本租户", "越权拒绝", "有审计"],
     ["pytest tests/ -k export -v", "ruff check app/"]),
    ("CLI-001", "migrate 与管理员命令（交付 D3）", "P1", "2027-03-05", ["SEC-004"], "L1", "cli-migrate-admin",
     "没有迁移命令，也不能用命令创建管理员。",
     ["管理员目前靠环境变量创建。"],
     ["app/services/auth_service.py", "README.md"],
     ["docs/plans/plan_remaining_delivery.md", "app/", "README.md", "tests/", "tasks.yaml", "AGENTS.md"],
     ["迁移命令可在空库执行", "创建管理员命令幂等且拒绝重复", "密码不进日志"],
     ["不实现 start、stop、logs 全集"],
     ["迁移后可启动", "命令创建的管理员可登录", "重复创建被拒绝"],
     ["迁移可启动", "管理员可登录", "重复拒绝"],
     ["按命令说明执行 migrate 和创建管理员并记录结果"]),
    ("REL-001", "Swagger 覆盖现有端点（交付 D4）", "P1", "2027-03-25", ["CLI-001"], "L0", "openapi-coverage",
     "已注册路由没有和 OpenAPI 对过账。",
     ["框架会生成 OpenAPI。缺少路由覆盖测试。"],
     ["app/main.py", "app/api/router.py"],
     ["docs/plans/plan_remaining_delivery.md", "tests/", "app/api/", "tasks.yaml", "AGENTS.md"],
     ["每个业务路由都出现在 OpenAPI 中"],
     ["不手写第二份 API 文档"],
     ["覆盖测试通过"],
     ["路由都在 OpenAPI 中"],
     ["pytest tests/ -k openapi -v"]),
    ("REL-002", "备份步骤与一次恢复记录（交付 D4）", "P1", "2027-03-25", ["CLI-001"], "L1", "backup-restore-record",
     "没有备份步骤，也没有一次恢复记录。",
     ["默认数据在 SQLite 文件。"],
     ["app/core/config.py", "README.md"],
     ["docs/plans/plan_remaining_delivery.md", "docs/", "README.md", "tasks.yaml", "AGENTS.md"],
     ["写明默认数据库如何备份", "在非生产副本上留下一次恢复记录"],
     ["不备份生产库", "不做自动异地容灾"],
     ["记录包含命令、结果和回滚方式"],
     ["有命令", "有结果", "有回滚"],
     ["在副本上执行一次备份和恢复并记录"]),
    ("REL-003", "测试门禁（交付 D4）", "P1", "2027-03-25", ["REL-001"], "L0", "release-test-gate",
     "发布前没有一份完整的测试、lint 和前端构建记录。",
     ["命令分散在各任务中。"],
     ["tasks.yaml", "frontend/package.json"],
     ["docs/plans/plan_remaining_delivery.md", "docs/plans/", "tasks.yaml", "AGENTS.md"],
     ["记录后端测试、ruff、前端类型检查和构建的退出码"],
     ["不把未跑出的覆盖率写成达标", "不跳过失败项"],
     ["记录包含命令、退出码和失败项"],
     ["命令有退出码"],
     ["pytest", "ruff check .", "cd frontend; npm run typecheck", "cd frontend; npm run build"]),
    ("REL-004", "一轮检索实验结论（交付 D4）", "P1", "2027-03-25", ["REL-003"], "L1", "one-retrieval-experiment",
     "独立重排或查询变换还没有一轮有结论的实验。",
     ["检索基线已冻结。不得同时更换 Embedding、切分和重排。"],
     ["docs/adr/0002-official-vectorstore.md", "evals/"],
     ["docs/plans/plan_remaining_delivery.md", "docs/", "evals/", "app/rag/", "tests/", "tasks.yaml", "AGENTS.md"],
     ["只改一个变量", "有提升则保留并记录指标", "无提升则恢复并记录不采纳"],
     ["不同时更换 Embedding、切分和重排", "不用 Mock Embedding 声称质量提升", "不改写已冻结基线文件"],
     ["结论写明变量、命令、指标和是否采纳"],
     ["单一变量", "有指标", "有采纳结论"],
     ["运行一轮检索评测并写入结论"]),
]


def block(item: tuple) -> str:
    (
        tid, title, priority, target, depends, level, side_effect,
        problem, facts, evidence, allowed, deliverables, non_goals,
        acceptance, cases, commands,
    ) = item
    dep = "\n".join(f'      - "{d}"' for d in depends)
    fact_lines = []
    for claim, ev in zip(facts, evidence, strict=False):
        fact_lines.append(f'        - claim: "{claim}"')
        fact_lines.append(f'          evidence: "{ev}"')
    if len(facts) > len(evidence):
        raise SystemExit(f"facts/evidence mismatch: {tid}")
    lines = [
        f'  - id: "{tid}"',
        f'    title: "{title}"',
        '    status: "ready"',
        f'    priority: "{priority}"',
        f'    target_date: "{target}"',
        "    depends_on:",
        dep,
        "    context:",
        f'      problem: "{problem}"',
        "      facts:",
        *fact_lines,
        "    scope:",
        "      allowed_paths:",
        *[f'        - "{p}"' for p in allowed],
        "      forbidden_paths:",
        *[f'        - "{p}"' for p in FORBIDDEN],
        "      deliverables:",
        *[f'        - "{p}"' for p in deliverables],
        "      non_goals:",
        *[f'        - "{p}"' for p in non_goals],
        "    acceptance:",
        *[f'      - "{p}"' for p in acceptance],
        "    risk:",
        f'      level: "{level}"',
        f'      side_effect: "{side_effect}"',
        '      rollback: "回退本任务提交，不改动已冻结的检索基线。"',
        "    evaluation:",
        "      cases:",
        *[f'        - "{p}"' for p in cases],
        "      commands:",
        *[f'        - "{p}"' for p in commands],
        "    execution:",
        '      owner: "个人开发者"',
        '      blocked_by: ""',
        "      nightly:",
        "        eligible: false",
        "        production_access: false",
        "        auto_merge: false",
        "        auto_deploy: false",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    text = TASKS.read_text(encoding="utf-8")
    if not text.endswith("\n"):
        text += "\n"
    addition = "\n".join(block(item) for item in ITEMS)
    TASKS.write_text(text + addition, encoding="utf-8")
    import yaml
    data = yaml.safe_load(TASKS.read_text(encoding="utf-8"))
    ids = [t["id"] for t in data["tasks"]]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate task id")
    expected = [item[0] for item in ITEMS]
    missing = [i for i in expected if i not in ids]
    if missing:
        raise SystemExit(f"missing {missing}")
    print(f"tasks={len(ids)} added={len(ITEMS)}")


if __name__ == "__main__":
    main()
